"""empty message

Revision ID: 7deb358d1808
Revises: c1573c134954
Create Date: 2016-05-29 05:53:48.585813

"""

# revision identifiers, used by Alembic.
revision = '7deb358d1808'
down_revision = 'c1573c134954'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=130), nullable=False),
    sa.Column('profile_url', sa.String(length=130), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('no_goals_added', sa.Integer(), nullable=True),
    sa.Column('no_goals_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=130), nullable=True),
    sa.Column('no_added', sa.Integer(), nullable=True),
    sa.Column('no_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], )
    )
    op.create_table('usergoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date_target', sa.DateTime(), nullable=True),
    sa.Column('privacy', sa.SmallInteger(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('successstory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_goal_id', sa.Integer(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=130), nullable=True),
    sa.Column('video_url', sa.String(length=130), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_goal_id'], ['usergoal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goal_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_goal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_goal_id'], ['usergoal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_story_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success_story_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['success_story_id'], ['successstory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=130), nullable=False),
    sa.Column('profile_url', mysql.VARCHAR(length=130), nullable=True),
    sa.Column('about_me', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('no_goals_added', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('no_goals_completed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('success_story_like')
    op.drop_table('user_goal_like')
    op.drop_table('successstory')
    op.drop_table('usergoal')
    op.drop_table('association')
    op.drop_table('list')
    op.drop_table('goal')
    op.drop_table('user')
    op.drop_table('category')
    ### end Alembic commands ###
