"""empty message

Revision ID: 83321e0f99d6
Revises: bd1342346b09
Create Date: 2016-07-12 22:42:25.869673

"""

# revision identifiers, used by Alembic.
revision = '83321e0f99d6'
down_revision = 'bd1342346b09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=130), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    ### end Alembic commands ###
