"""empty message

Revision ID: bd1342346b09
Revises: 7deb358d1808
Create Date: 2016-06-27 03:18:17.196954

"""

# revision identifiers, used by Alembic.
revision = 'bd1342346b09'
down_revision = '7deb358d1808'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_number', sa.String(length=12), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact_number')
    ### end Alembic commands ###
