"""empty message

Revision ID: c1573c134954
Revises: None
Create Date: 2016-05-22 06:38:14.823222

"""

# revision identifiers, used by Alembic.
revision = 'c1573c134954'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=130), nullable=False),
    sa.Column('profile_url', sa.String(length=130), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('no_goals_added', sa.Integer(), nullable=True),
    sa.Column('no_goals_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
