"""empty message

Revision ID: f658975ecb8b
Revises: None
Create Date: 2016-08-31 01:53:06.528947

"""

# revision identifiers, used by Alembic.
revision = 'f658975ecb8b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=130), nullable=True),
    sa.Column('no_added', sa.Integer(), nullable=True),
    sa.Column('no_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=130), nullable=False),
    sa.Column('email', sa.String(length=130), nullable=False),
    sa.Column('contact_number', sa.String(length=12), nullable=True),
    sa.Column('profile_url', sa.String(length=130), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('no_goals_added', sa.Integer(), nullable=True),
    sa.Column('no_goals_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usergoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date_target', sa.DateTime(), nullable=True),
    sa.Column('privacy', sa.SmallInteger(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('successstory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_goal_id', sa.Integer(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=130), nullable=True),
    sa.Column('video_url', sa.String(length=130), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_goal_id'], ['usergoal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_goal_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_goal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_goal_id'], ['usergoal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_story_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success_story_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['success_story_id'], ['successstory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('success_story_like')
    op.drop_table('user_goal_like')
    op.drop_table('successstory')
    op.drop_table('usergoal')
    op.drop_table('list')
    op.drop_table('user')
    op.drop_table('goal')
    ### end Alembic commands ###
