"""empty message

Revision ID: f792e9258771
Revises: f658975ecb8b
Create Date: 2016-08-31 02:35:18.494779

"""

# revision identifiers, used by Alembic.
revision = 'f792e9258771'
down_revision = 'f658975ecb8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goal', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.drop_column('goal', 'user_id')
    ### end Alembic commands ###
